title: Ethel Karskens # your name (or website title) here
logo: "ethel_civi.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  +5 years in data analysis and data science
  Master of Sciences in Econometrics 
  Network theories, Suspicious transactions analysis, 
 
  <br><br>
  Python, R, SQL expert 
  Confident in Tableau, Power BI 
  
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
